name: Regressivo QAzando
on: #momento que vai ser executando
  pull_request:
    branches: [master]
jobs:
  cypress-run:
      runs-on: ubuntu-latest
      steps:
      - name: Clonar o projeto
        uses: actions/checkout@v6

      - name: cypress runs-on
        uses: cypress-io/github-action@v7
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: 7fe3160d-8b68-4276-9a64-332554cbd535